config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  root "jobs#index"
  resources :jobs do
  resources :tasks
end
  get 'aanmelden' => 'users#new'
  get "inloggen" => "sessions#new"
  get 'archief' => "jobs#archief"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  mount_uploader :file, AttachmentUploader
  belongs_to :job
  validates :description, presence: true

 def self.search(search)
    where("description LIKE ? OR contactperson LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_signin
  before_action :set_job
  before_action :set_task, only: [:show, :edit, :update, :destroy]


  # GET /tasks
  # GET /tasks.json
  def index
      if params[:search]
      @tasks = @job.tasks.search(params[:search]).paginate(page: params[:page], per_page: 5).order('id DESC')
    else
      @tasks = @job.tasks.paginate(page: params[:page], per_page: 5).order('id DESC')
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @job.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @job.tasks.build(task_params)
    @task.contactperson = current_user.name

    respond_to do |format|
      if @task.save
        format.html { redirect_to job_tasks_path(@job), notice: 'Taak is succesvol opgeslagen.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @task.contactperson = current_user.name
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to job_tasks_path(@job), notice: 'Taak is succesvol opgeslagen.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to job_tasks_path(@job), notice: 'Taak is verwijderd.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:job_id])
    end

    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :file, :remove_file, :contactperson)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: [job, task], local: true, :html => {multipart: true}) do |form| %>
  <%= render "Shared/errors", object: task %>

<form>
  <div class="form_group">
    <%= form.label :Omschrijving, class: 'form-control-label' %>
    <%= form.text_area :description, id: :task_description, class: 'form-control' %>
  </div>

  <div class="form_group">
    <%= form.label :Bestand, class: 'form-control-label' %>
    <%= form.file_field :file, class: 'form-control' %>
  </div>
  <%= form.check_box :remove_file %> Verwijder bestand

<br>
  <div class="btn-group" role="group">
    <%= form.submit "Opslaan", :class => "btn btn-secondary" %>
  </div>
<% end %>

</form>

app/views/tasks/edit.html.erb
<h1>Taak aanpassen</h1>

  <%= render 'form',job: @job, task: @task %>
<br>
<div>
  <%= link_to 'Taak weergeven', job_task_path(@job, @task), :class => "btn btn-secondary" %>
  <%= link_to 'Overzicht taken', job_tasks_path(@job), :class => "btn btn-secondary" %>
</div>

app/views/tasks/index.html.erb
<h1>Taken</h1>

  <div class="table-responsive">
    <table class="table table-striped table-bordered table">
      <thead class="thead-inverse">
        <tr>
          <th>Datum</th>
          <th>Omschrijving</th>
          <th>File</th>
          <th>Door</th>
        </tr>
      </thead>

      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td><%= task.created_at.to_date.iso8601 %></td>
            <td><%= link_to task.description, job_task_path(@job, task) %></td>
            <td><%= link_to (task.file_identifier), task.file.url, target: '_blank' if task.file? %></td>
            <td><%= task.contactperson %></td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
    <br>
  <div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @jobs %>
  </div>
  <%= will_paginate @jobs, :container => false %>
</div>
  <div>
    <%= link_to 'Nieuwe taak', new_job_task_path, :class => "btn btn-secondary"  %>
  </div>

app/views/tasks/new.html.erb
<h1>Nieuwe taak</h1>

  <%= render 'form',job: @job, task: @task %>
<br>
<div>
  <%= link_to 'Overzicht taken', job_tasks_path, :class => "btn btn-secondary" %>
</div>

app/views/tasks/show.html.erb
<div>
  <ul class="list-group">
    <li class="list-group-item">
      <strong>Datum:&nbsp;</strong>
      <%= @task.created_at.to_date.iso8601 %>
    </li>

    <li class="list-group-item">
      <strong>Omschrijving:&nbsp;</strong>
      <%= @task.description %>
    </li>

    <li class="list-group-item">
      <strong>File:&nbsp;</strong>
      <%=  link_to (@task.file_identifier), @task.file.url, target: '_blank' if @task.file? %>
    </li>

    <li class="list-group-item">
      <strong>Door:&nbsp;</strong>
      Contactpersoon koppelen
    </li>

  </ul>
  <br>
  <div class="btn-group" role="group">
    <%= link_to 'Overzicht taken', job_tasks_path(@job), :class => "btn btn-secondary" %>
    <%= link_to 'Taak aanpassen', edit_job_task_path(@job, @task), :class => "btn btn-secondary" %>
    <%= link_to 'Taak verwijderen', job_task_path(@job, @task), method: :delete, data: { confirm: 'Zeker weten?' },
                                                       :class => "btn btn-secondary" %>
  </div>
</div>