config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  root "jobs#index"
  resources :jobs do
  resources :tasks
end
  get 'aanmelden' => 'users#new'
  get "inloggen" => "sessions#new"
  get 'archief' => "jobs#archief"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  JOBSTATUS= ['Actief', 'Archief']
	has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks
  validates :contactperson, :title, :article_number, presence: true
  scope :active, -> { where(status: "Actief") }
  scope :archive, -> { where(status: "Archief") }

  def self.search(search)
    where("title LIKE ? OR article_number LIKE ? OR contactperson LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :require_signin
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    if params[:search]
      @jobs = Job.active.search(params[:search]).paginate(page: params[:page], per_page: 5).order('id DESC')
    else
      @jobs = Job.active.paginate(page: params[:page], per_page: 5).order('id DESC')
    end
  end

  def archief
    if params[:search]
      @jobs = Job.archive.(params[:search]).paginate(page: params[:page], per_page: 5).order('id DESC')
    else
      @jobs = Job.archive.paginate(page: params[:page], per_page: 5).order('id DESC')
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job is succesvol opgeslagen.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job is succesvol opgeslagen.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job is verwijderd.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:contactperson, :title, :description, :article_number, :status)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
    <%= render "Shared/errors", object: job %>

  <form>
    <div class="form-group">
      <%= form.label :contactpersoon, class: 'form-control-label' %>
      <%= form.collection_select(:contactperson, User.all, :name, :name, {prompt: "Selecteer een gebruiker"}, {class: 'form-control'}) %>
    </div>

    <div class="form-group">
      <%= form.label :titel, class: 'form-control-label' %>
      <%= form.text_field :title, id: :job_title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :omschrijving, class: 'form-control-label' %>
      <%= form.text_area :description, id: :job_description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :artikelnummer, class: 'form-control-label' %>
      <%= form.text_field :article_number, id: :job_article_number, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :status, class: 'form-control-label' %>
      <%= form.select :status, Job::JOBSTATUS, id: :job_status, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit "Opslaan", :class => "btn btn-secondary" %>
    </div>
  <% end %>
</form>

app/views/jobs/archief.html.erb
<h4>Overzicht archief jobs</h4>


<div class="table-responsive">
<table class="table table-striped table-bordered table">
  <thead class="thead-inverse">
    <tr>
      <th>Jobnr</th>
      <th>Artikelnummer</th>
      <th>Titel</th>
      <th>Actie</th>
      <th>Laatste actie</th>
      <th>Status</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr class = <%= find_company_name(job) %>>
        <td><%= link_to job.id, job %></td>
        <td><%= job.article_number %></td>
        <td><%= link_to job.title, job %></td>
        <td><%= find_description(job) %></td>
        <td><%= find_company_name(job) %></td>
        <td><%= job.status %></td>
        <td><%= link_to 'Taken', job_tasks_path(job) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/jobs/edit.html.erb
<h1>Job aanpassen</h1>

<%= render 'form', job: @job %>
<br>
<%= link_to 'Overzicht jobs', jobs_path, :class => "btn btn-secondary" %>

app/views/jobs/index.html.erb
<h4>Overzicht jobs</h4>


<div class="table-responsive">
<table class="table table-striped table-bordered table">
  <thead class="thead-invers">
    <tr>
      <th>Jobnr</th>
      <th>Artikelnummer</th>
      <th>Titel</th>
      <th>Actie</th>
      <th>Laatste actie</th>
      <th>Status</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr class = <%= find_company_name(job) %>>
        <td><%= link_to job.id, job %></td>
        <td><%= job.article_number %></td>
        <td><%= link_to job.title, job %></td>
        <td><%= find_description(job) %></td>
        <td><%= find_company_name(job) %></td>
        <td><%= job.status %></td>
        <td><%= link_to 'Taken', job_tasks_path(job) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @jobs %>
  </div>
  <%= will_paginate @jobs, :container => false %>
</div>
<div>
<%= link_to 'Nieuwe Job', new_job_path, :class => "btn btn-secondary"  %>
</div>

app/views/jobs/new.html.erb
<h1>Nieuwe Job</h1>

<%= render 'form', job: @job %>
<br>
<%= link_to 'Overzicht jobs', jobs_path, :class => "btn btn-secondary" %>

app/views/jobs/show.html.erb
<div>
  <ul class="list-group">
    <li class="list-group-item">
    <strong>Contactpersoon:&nbsp;</strong>
    <%= @job.contactperson %>
    </li>

    <li class="list-group-item">
    <strong>Titel:&nbsp;</strong>
    <%= @job.title %>
    </li>

    <li class="list-group-item">
    <strong>Omschrijving:&nbsp;</strong>
    <%= @job.description %>
    </li>

    <li class="list-group-item">
    <strong>Artikel nummer:&nbsp;</strong>
    <%= @job.article_number %>
    </li>

    <li class="list-group-item">
    <strong>Status:&nbsp;</strong>
    <%= @job.status %>
    </li>

  </ul>
  <br>
  <div class="btn-group" role="group">
    <%= link_to 'Overzicht jobs', jobs_path, :class => "btn btn-secondary" %>
    <%= link_to 'Taken', job_tasks_path(@job), :class => "btn btn-secondary" %>
    <%= link_to 'Aanpassen', edit_job_path(@job), :class => "btn btn-secondary" %>
    <%= link_to 'Verwijderen', job_path(@job), method: :delete, data: { confirm: 'Zeker weten?' },
                                                                     :class => "btn btn-secondary" %>
  </div>
</div>