config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  root "jobs#index"
  resources :jobs do
  resources :tasks
end
  get 'aanmelden' => 'users#new'
  get "inloggen" => "sessions#new"
  get 'archief' => "jobs#archief"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/Shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h3>
      Foutje! De <%= object.class.name.titleize.downcase %> kon niet worden opgeslagen.
    </h3>
    <h4>
      Corrigeer aub de volgende fouten <%= pluralize(object.errors.count, "error") %>:
    </h4>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>

app/views/Shared/_footer.html.erb
<footer class="footer">
<div class="container">
  <p class= "text-center">
  <span class="text-muted">@<%= Time.current.year %> Zalsman All rights reserved.</span>
  </p>
</div>
</footer>

app/views/Shared/_topbar.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
	
  <a class="navbar-brand" href="/"><%= image_tag 'logo-auping.png' %></a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_url, :class => "nav-link"  %> <span class="sr-only">(current)</span></a>
      </li>
      <% if current_user %>
      <li class="nav-item">
        <%= link_to "Jobs", jobs_path, :class => "nav-link"  %>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">Acties
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Jobs", jobs_path, :class => "dropdown-item"  %>
          <%= link_to "Archief", archief_path, :class => "dropdown-item"  %>
        </div>
      </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <ul class="navbar-nav mr-auto">
      <% if current_user %>
        <li class="nav-item">
        <%= link_to current_user.name, current_user, :class => "nav-link"  %>
        </li>
        <li class="nav-item">
        <%= link_to 'Uitloggen', session_path, method: :delete, :class => "nav-link" %>
      </li>
      <% end %>
        <% if current_user && current_user.admin? %>
        <li class="nav-item">
        <%= link_to "Gebruikers instellingen", users_path, :class => "nav-link"  %>
      </li>
      <% end %>
      </ul>
       <%= form_tag(jobs_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Zoeken", :class=> "form-control mr-sm-2" %>
        <%= submit_tag "Zoeken", :name => nil, :class => "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </form>
  </div>
</nav>